default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: newulife_payment_droplet_development
  queue:
    <<: *default
    database: newulife_payment_droplet_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: newulife_payment_droplet_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>


production:
  primary: &primary_production
    <<: *default
    database: newulife_payment_droplet_production
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: newulife_payment_droplet_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: newulife_payment_droplet_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: newulife_payment_droplet_production_cable
    migrations_paths: db/cable_migrate
